name = "ComminWeath"
uuid = "25066647-bad8-40d7-98fa-f0e92ffc8a6d"
authors = ["Graham Harper Edwards"]
version = "1.0.0-DEV"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"

[compat]
ColorSchemes = "3"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
